### ISSUE TITLE
Removing white space under text in writeHTMLCell

### ISSUE THREAD

**Issue by DrLightman** [tecnickcom/TCPDF#239]
I'm using writeHTMLCell to print some simple HTML, like this:

```php
<?php
ob_start();
?>
<p class="ppnx_11_title">bla bla bla</p>
<p class="ppnx_11_subtitle">bla bla bla</p>
<?php
$html = ob_get_clean();

$pdf->writeHTMLCell(
    0, // $wx (float)
    0, // $wy (float)
    $margins['left'], // $x (float)
    $pdf->GetY(), // $y (float)
    $html, // $html (string)
    1, // $border (mixed)
    0, // $ln (int)
    false, // $fill (boolean)
    true, // $reseth (boolean)
    '', // $align (string)
    false // $autopadding (boolean)
);
```

But despite attempts to style the paragraphs (using DIVs makes not difference) I can't get rid of all that white space in between them and at the bottom of the cell.

Tried with a CSS like this:

```css
.ppnx-11-title { line-height:0; margin-bottom:0; padding-bottom:0; }
.ppnx-11-subtitle { line-height:0; margin-bottom:0; padding-bottom:0; }
```

But not only it didn't work, it also made the thing slightly worse.

![spaces](https://user-images.githubusercontent.com/4699807/84871787-413ce100-b081-11ea-88fb-e0713e75fb55.jpg)

The test PDF: [20200617075508-posts.pdf](https://github.com/tecnickcom/TCPDF/files/4791120/20200617075508-posts.pdf)

Do you have any idea how to control those spaces?
